hw-1
timurio111/hse_ml_course_2024 pull request #1
Opened 2024-02-01 22:46 UTC by timurio111

2024-02-03 11:59 UTC, svkov requested changes
Ставлю 0.4, добавь тестирование первой задачки

2024-02-03 11:59 UTC, svkov commented on data/dota_hero_stats.csv
Данные надо убрать из репо

2024-02-03 11:59 UTC, svkov commented on notebooks/01-homework.ipynb
> +    "def func(arr : list) -> dict:\n",
А где ячейка с запуском кода? Верю, что работает, но все же лучше их добавить)

2024-02-04 18:50 UTC, timurio111 commented on data/dota_hero_stats.csv
> Данные надо убрать из репо

done

2024-02-04 18:51 UTC, timurio111 commented
> Ставлю 0.4, добавь тестирование первой задачки

я побаловался немного и написал простенький стресс тест 🤓

2024-02-04 18:52 UTC, timurio111 commented on notebooks/01-homework.ipynb
> +    "def func(arr : list) -> dict:\n",
> А где ячейка с запуском кода? Верю, что работает, но все же лучше их добавить)

я побаловался немного и написал простенький стресс тест 🤓

2024-02-10 08:01 UTC, svkov approved these changes
Супер

2024-02-10 11:10 UTC, merged